# Wrap around to communicate Widget to PCL smach status, False or True

bool stopped_state
bool idle_state
bool starting_state
bool execute_state
bool completing_state
bool complete_state
bool clearing_state
bool suspended_state
bool aborting_state
bool aborted_state
bool holding_state
bool held_state
bool unholding_state
bool suspending_state
bool unsuspending_state
bool resetting_state
bool stopping_state
